### ISSUE TITLE
Error processing Puerto Rico geojson

### ISSUE THREAD

**Issue by dmcglone** [PublicMapping/districtbuilder#1092]
When running the `process-geojson` script on Puerto Rico data, it results in an error when writing the geojson. See below:
```
Exploding Multi* and GeometryCollection geometries into flat geometries and labelling only the largest part.
/home/node/app/manage/node_modules/geojson-polygon-labels/bin/geojson-polygon-labels:144
                .reduce((prev, current) => (turf.area(prev) > turf.area(current)) ? prev : current)];
                 ^

TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at labelFeature (/home/node/app/manage/node_modules/geojson-polygon-labels/bin/geojson-polygon-labels:144:18)
    at Stream.<anonymous> (/home/node/app/manage/node_modules/geojson-polygon-labels/bin/geojson-polygon-labels:105:13)
    at Stream.stream.write (/home/node/app/manage/node_modules/through/index.js:26:11)
    at Stream.ondata (internal/streams/legacy.js:19:31)
    at Stream.emit (events.js:314:20)
    at drain (/home/node/app/manage/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/home/node/app/manage/node_modules/through/index.js:45:5)
    at Parser.parser.onValue (/home/node/app/manage/node_modules/JSONStream/index.js:118:16)
    at Parser.proto.emit (/home/node/app/manage/node_modules/jsonparse/jsonparse.js:337:8)
Error: Command failed: node_modules/.bin/geojson-polygon-labels --style=largest data/output-pr/blockgroup.geojson >data/output-pr/blockgroup-labels.geojson
Exploding Multi* and GeometryCollection geometries into flat geometries and labelling only the largest part.
/home/node/app/manage/node_modules/geojson-polygon-labels/bin/geojson-polygon-labels:144
                .reduce((prev, current) => (turf.area(prev) > turf.area(current)) ? prev : current)];
                 ^
TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at labelFeature (/home/node/app/manage/node_modules/geojson-polygon-labels/bin/geojson-polygon-labels:144:18)
    at Stream.<anonymous> (/home/node/app/manage/node_modules/geojson-polygon-labels/bin/geojson-polygon-labels:105:13)
    at Stream.stream.write (/home/node/app/manage/node_modules/through/index.js:26:11)
    at drain (/home/node/app/manage/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/home/node/app/manage/node_modules/through/index.js:45:5)
    at Parser.parser.onValue (/home/node/app/manage/node_modules/JSONStream/index.js:118:16)
    at Parser.proto.emit (/home/node/app/manage/node_modules/jsonparse/jsonparse.js:337:8)
    at shellExec (/home/node/app/manage/src/lib/cmd.js:11:15)
    at execCmd (/home/node/app/manage/src/lib/cmd.js:44:3)
    at Object.geojsonPolygonLabels (/home/node/app/manage/src/lib/cmd.js:49:5)
    at /home/node/app/manage/src/commands/process-geojson.ts:756:7
    at Array.forEach (<anonymous>)
    at ProcessGeojson.writeVectorTiles (/home/node/app/manage/src/commands/process-geojson.ts:739:15)
    at ProcessGeojson.run (/home/node/app/manage/src/commands/process-geojson.ts:263:40)
    at runMicrotasks (<anonymous>)
```
Geojson:
[pr_1620.zip](https://github.com/PublicMapping/districtbuilder/files/7810421/pr_1620.zip)

Process geojson code:
` ./scripts/manage process-geojson data/pr_1620.geojson -d population:population,white:white,black:black,hispanic:hispanic,asian:asian,native:native,pacific:pacific -l block:block,blockgroup:blockgroup,county:county -n 12,4,4 -o data/output-pr -x 12,12,12`

**Comment by ktohalloran** [comment]
Ok, so the issue here is with the Puerto Rico geojson file. It has two major problems: 
1) Every block in the file has a duplicate--same block ID, same geometries, same properties, everything. This creates a faulty `topo.json` that prevents the blocks from being properly merged into blockgroups and counties. 
2) The special characters in the following counties are misrepresented in the geojson, e.g. "Añasco" is listed as "A\u00c3\u00b1asco" in the geojson. The effected counties are:
* Añasco
* Bayamón
* Canóvanas
* Cataño
* Comerío
* Guánica
* Juana Díaz
* Las Marías
* Loíza
* Manatí
* Mayagüez
* Peñuelas
* Rincón
* Río Grande
* San Germán
* San Sebastián

This file runs as it should once duplicates have been removed and special characters fixed. I spoke with @maurizi about this and he said that the best way forward following identification of the issues was to speak with Brian about fixing the data. Please let me know if there's anything else I can provide, such as the script I wrote to make the changes listed above.
