### ISSUE TITLE
Jenkins e2e tests sometimes hang indefinitely

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#1189]
Tests on Jenkins are _sometimes_ hanging_ indefinitely.

Test output shows the following:
```
$ jest --config ./test/jest-e2e.json --watchAll=false
[Nest] 29  - 04/05/2022, 4:07:48 PM   DEBUG [worker-pool] Object:
{
  "dockerMemLimit": "12 GB",
  "hostmem": "23.52 GB",
  "maxCacheSize": "115.2 MB"
}

FAIL test/districts.controller.e2e-spec.ts (181.575 s)
  ● DistrictsController › import plan from block equivalency CSV › should return a districts definition

    Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().

      at Timeout._onTimeout (../node_modules/threads/dist/master/spawn.js:35:53)

  ● DistrictsController › import plan from block equivalency CSV › should return a districts definition

    Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().

      at Timeout._onTimeout (../node_modules/threads/dist/master/spawn.js:35:53)

  ● DistrictsController › import plan from block equivalency CSV › should return a districts definition

    Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().

      at Timeout._onTimeout (../node_modules/threads/dist/master/spawn.js:35:53)

  ● DistrictsController › import plan from block equivalency CSV › should return a districts definition

    Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().

      at Timeout._onTimeout (../node_modules/threads/dist/master/spawn.js:35:53)

  ● DistrictsController › import plan from block equivalency CSV › should return a districts definition

    Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().

      at Timeout._onTimeout (../node_modules/threads/dist/master/spawn.js:35:53)

  ● DistrictsController › import plan from block equivalency CSV › should return a districts definition

    Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().

      at Timeout._onTimeout (../node_modules/threads/dist/master/spawn.js:35:53)

  ● DistrictsController › import plan from block equivalency CSV › should return a districts definition

    Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().

      at Timeout._onTimeout (../node_modules/threads/dist/master/spawn.js:35:53)

  ● DistrictsController › import plan from block equivalency CSV › should return a districts definition

    Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().

      at Timeout._onTimeout (../node_modules/threads/dist/master/spawn.js:35:53)

  ● DistrictsController › import plan from block equivalency CSV › should return a districts definition

    Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().

      at Timeout._onTimeout (../node_modules/threads/dist/master/spawn.js:35:53)

  ● DistrictsController › import plan from block equivalency CSV › should return a districts definition

    Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().

      at Timeout._onTimeout (../node_modules/threads/dist/master/spawn.js:35:53)

  ● DistrictsController › import plan from block equivalency CSV › should return a districts definition

    Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().

      at Timeout._onTimeout (../node_modules/threads/dist/master/spawn.js:35:53)

  ● DistrictsController › import plan from block equivalency CSV › should return a districts definition

    Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().

      at Timeout._onTimeout (../node_modules/threads/dist/master/spawn.js:35:53)

  ● DistrictsController › import plan from block equivalency CSV › should return a districts definition

    Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().

      at Timeout._onTimeout (../node_modules/threads/dist/master/spawn.js:35:53)

  ● DistrictsController › import plan from block equivalency CSV › should return a districts definition

    Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().

      at Timeout._onTimeout (../node_modules/threads/dist/master/spawn.js:35:53)

  ● DistrictsController › import plan from block equivalency CSV › should return a districts definition

    thrown: "Exceeded timeout of 50000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      51 |
      52 |   describe("import plan from block equivalency CSV", () => {
    > 53 |     it("should return a districts definition", () => {
         |     ^
      54 |       return request(app.getHttpServer())
      55 |         .post("/api/districts/import/csv")
      56 |         .attach("file", `${__dirname}/data/de.csv`)

      at districts.controller.e2e-spec.ts:53:5
      at districts.controller.e2e-spec.ts:52:3
      at Object.<anonymous> (districts.controller.e2e-spec.ts:13:1)

  ● DistrictsController › import plan from block equivalency CSV with invalid block id in first row › should return a flag

    Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().

      at Timeout._onTimeout (../node_modules/threads/dist/master/spawn.js:35:53)

  ● DistrictsController › import plan from block equivalency CSV with invalid block id in first row › should return a flag

    thrown: "Exceeded timeout of 50000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
 ```

**Comment by BryanQuigley** [comment]
Is this too big memory wise to consider moving to GH actions?

**Comment by maurizi** [comment]
> Is this too big memory wise to consider moving to GH actions?

Definitely not - the only state we load to run tests is DE (very tiny).
Doubtful that its something specific to Jenkins that's causing the hanging issue - I could be wrong though?
